"""platform tables: jobs, run trace, evidence, manifests, investigations, data
quality, copilot, scenarios, semantic layer, evaluation runs

Additive only: 17 new tables, and new nullable columns on alerts, questions,
dataset_versions and scheduled_analyses. No existing column is altered and no
row is rewritten, so it is safe on a populated database.

Autogenerated against Postgres, then edited: autogenerate wanted to drop
ix_analysis_memories_embedding (the pgvector HNSW index created with raw SQL in
b7c9d1e2f3a4, which the models do not declare). That drop was removed -- this
migration must not touch it.

Revision ID: f1a3b5c7d9e2
Revises: e0f2a4b6c8d1
Create Date: 2026-10-10 03:04:20
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1a3b5c7d9e2'
down_revision: Union[str, Sequence[str], None] = 'e0f2a4b6c8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_version', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('git_sha', sa.String(), nullable=True),
    sa.Column('summary_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_id'), 'eval_runs', ['id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('metrics_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('detail_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_case_id'), 'eval_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_eval_results_id'), 'eval_results', ['id'], unique=False)
    op.create_index(op.f('ix_eval_results_run_id'), 'eval_results', ['run_id'], unique=False)
    op.create_table('semantic_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_metrics_id'), 'semantic_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_metrics_slug'), 'semantic_metrics', ['slug'], unique=False)
    op.create_index(op.f('ix_semantic_metrics_team_id'), 'semantic_metrics', ['team_id'], unique=False)
    op.create_table('semantic_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('src_type', sa.String(), nullable=False),
    sa.Column('src_ref', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('dst_type', sa.String(), nullable=False),
    sa.Column('dst_ref', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_relationships_id'), 'semantic_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_relationships_team_id'), 'semantic_relationships', ['team_id'], unique=False)
    op.create_table('semantic_metric_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('filters_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['semantic_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_metric_versions_id'), 'semantic_metric_versions', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_metric_versions_metric_id'), 'semantic_metric_versions', ['metric_id'], unique=False)
    op.create_table('semantic_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['semantic_metrics.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_terms_id'), 'semantic_terms', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_terms_team_id'), 'semantic_terms', ['team_id'], unique=False)
    op.create_index(op.f('ix_semantic_terms_term'), 'semantic_terms', ['term'], unique=False)
    op.create_table('copilot_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_sessions_id'), 'copilot_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_sessions_team_id'), 'copilot_sessions', ['team_id'], unique=False)
    op.create_index(op.f('ix_copilot_sessions_user_id'), 'copilot_sessions', ['user_id'], unique=False)
    op.create_table('dq_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('baseline_version_id', sa.Integer(), nullable=True),
    sa.Column('thresholds_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id')
    )
    op.create_index(op.f('ix_dq_configs_id'), 'dq_configs', ['id'], unique=False)
    op.create_index(op.f('ix_dq_configs_team_id'), 'dq_configs', ['team_id'], unique=False)
    op.create_table('dq_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('baseline_version_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('check_name', sa.String(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dq_incidents_dataset_id'), 'dq_incidents', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dq_incidents_dataset_version_id'), 'dq_incidents', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_dq_incidents_id'), 'dq_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_dq_incidents_team_id'), 'dq_incidents', ['team_id'], unique=False)
    op.create_table('dq_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id')
    )
    op.create_index(op.f('ix_dq_snapshots_dataset_id'), 'dq_snapshots', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dq_snapshots_id'), 'dq_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_dq_snapshots_team_id'), 'dq_snapshots', ['team_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('baseline_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('adjustments_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('results_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_scenarios_team_id'), 'scenarios', ['team_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('failure_class', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_analysis_jobs_id'), 'analysis_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_state'), 'analysis_jobs', ['state'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_team_id'), 'analysis_jobs', ['team_id'], unique=False)
    op.create_table('copilot_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('action_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('evidence_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['copilot_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_turns_id'), 'copilot_turns', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_turns_session_id'), 'copilot_turns', ['session_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('report_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_dataset_id'), 'investigations', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_investigations_id'), 'investigations', ['id'], unique=False)
    op.create_index(op.f('ix_investigations_question_id'), 'investigations', ['question_id'], unique=False)
    op.create_index(op.f('ix_investigations_team_id'), 'investigations', ['team_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('detail_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_events_id'), 'run_events', ['id'], unique=False)
    op.create_index(op.f('ix_run_events_question_id'), 'run_events', ['question_id'], unique=False)
    op.create_index(op.f('ix_run_events_team_id'), 'run_events', ['team_id'], unique=False)
    op.create_table('run_manifests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('dataset_fingerprint', sa.String(), nullable=True),
    sa.Column('manifest_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_run_manifests_id'), 'run_manifests', ['id'], unique=False)
    op.create_index(op.f('ix_run_manifests_team_id'), 'run_manifests', ['team_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.Column('element_id', sa.String(), nullable=True),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=True),
    sa.Column('metric_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('dataset_fingerprint', sa.String(), nullable=True),
    sa.Column('execution_log_id', sa.Integer(), nullable=True),
    sa.Column('artifact_refs_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('recomputed_value', sa.String(), nullable=True),
    sa.Column('checks_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('limitations_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reasons_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validity_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['execution_log_id'], ['execution_logs.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id')
    )
    op.create_index(op.f('ix_evidence_records_dashboard_id'), 'evidence_records', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_element_id'), 'evidence_records', ['element_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_id'), 'evidence_records', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_records_question_id'), 'evidence_records', ['question_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_team_id'), 'evidence_records', ['team_id'], unique=False)
    op.add_column('alerts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('dedup_key', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('occurrences', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_by', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('explanation_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('alerts', sa.Column('delivery_state', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('delivery_attempts', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('next_delivery_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('delivery_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.add_column('dataset_versions', sa.Column('content_sha256', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('route', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('rerun_of_question_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('clarification_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_index(op.f('ix_questions_rerun_of_question_id'), 'questions', ['rerun_of_question_id'], unique=False)
    op.add_column('scheduled_analyses', sa.Column('min_effect_abs', sa.Float(), nullable=True))
    op.add_column('scheduled_analyses', sa.Column('comparison', sa.String(), nullable=True))
    op.add_column('scheduled_analyses', sa.Column('window_runs', sa.Integer(), nullable=True))
    op.add_column('scheduled_analyses', sa.Column('suppress_on_dq', sa.Boolean(), nullable=True))
    op.add_column('scheduled_analyses', sa.Column('notify_email', sa.Boolean(), nullable=True))
    op.add_column('scheduled_analyses', sa.Column('last_processed_question_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_analyses', 'last_processed_question_id')
    op.drop_column('scheduled_analyses', 'notify_email')
    op.drop_column('scheduled_analyses', 'suppress_on_dq')
    op.drop_column('scheduled_analyses', 'window_runs')
    op.drop_column('scheduled_analyses', 'comparison')
    op.drop_column('scheduled_analyses', 'min_effect_abs')
    op.drop_index(op.f('ix_questions_rerun_of_question_id'), table_name='questions')
    op.drop_column('questions', 'clarification_json')
    op.drop_column('questions', 'rerun_of_question_id')
    op.drop_column('questions', 'route')
    op.drop_column('dataset_versions', 'content_sha256')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_column('alerts', 'delivery_payload_json')
    op.drop_column('alerts', 'next_delivery_at')
    op.drop_column('alerts', 'delivery_attempts')
    op.drop_column('alerts', 'delivery_state')
    op.drop_column('alerts', 'explanation_json')
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'resolved_by')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'acknowledged_by')
    op.drop_column('alerts', 'last_seen_at')
    op.drop_column('alerts', 'occurrences')
    op.drop_column('alerts', 'dedup_key')
    op.drop_column('alerts', 'severity')
    op.drop_column('alerts', 'status')
    op.drop_index(op.f('ix_evidence_records_team_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_question_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_element_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_dashboard_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_run_manifests_team_id'), table_name='run_manifests')
    op.drop_index(op.f('ix_run_manifests_id'), table_name='run_manifests')
    op.drop_table('run_manifests')
    op.drop_index(op.f('ix_run_events_team_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_question_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_investigations_team_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_question_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_dataset_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_copilot_turns_session_id'), table_name='copilot_turns')
    op.drop_index(op.f('ix_copilot_turns_id'), table_name='copilot_turns')
    op.drop_table('copilot_turns')
    op.drop_index(op.f('ix_analysis_jobs_team_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_state'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_scenarios_team_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_dq_snapshots_team_id'), table_name='dq_snapshots')
    op.drop_index(op.f('ix_dq_snapshots_id'), table_name='dq_snapshots')
    op.drop_index(op.f('ix_dq_snapshots_dataset_id'), table_name='dq_snapshots')
    op.drop_table('dq_snapshots')
    op.drop_index(op.f('ix_dq_incidents_team_id'), table_name='dq_incidents')
    op.drop_index(op.f('ix_dq_incidents_id'), table_name='dq_incidents')
    op.drop_index(op.f('ix_dq_incidents_dataset_version_id'), table_name='dq_incidents')
    op.drop_index(op.f('ix_dq_incidents_dataset_id'), table_name='dq_incidents')
    op.drop_table('dq_incidents')
    op.drop_index(op.f('ix_dq_configs_team_id'), table_name='dq_configs')
    op.drop_index(op.f('ix_dq_configs_id'), table_name='dq_configs')
    op.drop_table('dq_configs')
    op.drop_index(op.f('ix_copilot_sessions_user_id'), table_name='copilot_sessions')
    op.drop_index(op.f('ix_copilot_sessions_team_id'), table_name='copilot_sessions')
    op.drop_index(op.f('ix_copilot_sessions_id'), table_name='copilot_sessions')
    op.drop_table('copilot_sessions')
    op.drop_index(op.f('ix_semantic_terms_term'), table_name='semantic_terms')
    op.drop_index(op.f('ix_semantic_terms_team_id'), table_name='semantic_terms')
    op.drop_index(op.f('ix_semantic_terms_id'), table_name='semantic_terms')
    op.drop_table('semantic_terms')
    op.drop_index(op.f('ix_semantic_metric_versions_metric_id'), table_name='semantic_metric_versions')
    op.drop_index(op.f('ix_semantic_metric_versions_id'), table_name='semantic_metric_versions')
    op.drop_table('semantic_metric_versions')
    op.drop_index(op.f('ix_semantic_relationships_team_id'), table_name='semantic_relationships')
    op.drop_index(op.f('ix_semantic_relationships_id'), table_name='semantic_relationships')
    op.drop_table('semantic_relationships')
    op.drop_index(op.f('ix_semantic_metrics_team_id'), table_name='semantic_metrics')
    op.drop_index(op.f('ix_semantic_metrics_slug'), table_name='semantic_metrics')
    op.drop_index(op.f('ix_semantic_metrics_id'), table_name='semantic_metrics')
    op.drop_table('semantic_metrics')
    op.drop_index(op.f('ix_eval_results_run_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_case_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_eval_runs_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    # ### end Alembic commands ###
